name=ModbusTCP_RU
version=0.1.3
author=UterGrooll
maintainer=UterGrooll <UterGrooll@yandex.ru>
sentence=A Modbus TCP Slave/Master library for Arduino.
paragraph=ModbusTCP_RU provides Modbus TCP Master and Slave modes for Arduino boards using W5100 or W5500 Ethernet controllers. It supports standard Modbus functions for register and bit access and includes examples for relay control, sensor data exchange, and direct device-to-device communication.
category=Communication
url=https://github.com/UterGrooll/ModbusTCP_RU
architectures=avr,sam,stm32
